Überarbeitete Gateway-Doku
ffsh/docs pull request #11
Opened 2020-05-03 07:16 UTC by GitFlix

2020-05-03 07:21 UTC, GitFlix commented
Aufbau vereinheitlicht, Reihenfolge verändert, Elemente ergänzt.

2020-05-03 07:43 UTC, Grotax requested changes
Den EOF kram hätte ich gerne raus, sonst super Verbesserung zu vorher :)

2020-05-03 07:43 UTC, Grotax commented on gateway.rst
> +   EOF
Das mit dem EOF kann glaube ich weg, verstehe nicht wofür das da steht

2020-05-03 07:43 UTC, Grotax commented on gateway.rst
> +   EOF
ah ok habs einmal nachgesehen aber das ist nicht besonders intuitv finde ich.
Das gleiche für die anderen Verwendungen davon

2020-05-03 07:43 UTC, Grotax commented on gateway.rst
> +Um hier die Konfigurationen sauber zu halten lassen wir die defaults unangetastet. In :code: `/etc/network/interfaces` sind unter Debian 10 keine Interfaces mehr angegeben, sie werden aus Dateien in
nice :D

2020-05-03 07:43 UTC, Grotax commented on gateway.rst
> +Jetzt brauchenwir noch den dhcp innerhalb de FFSH-Netzes
leerzeichen :)

2020-05-03 07:43 UTC, Grotax commented on gateway.rst
> +    udo seradd -m -s /bin/bash dnsbind
sudo useradd

2020-05-03 07:43 UTC, Grotax commented on gateway.rst
> +Das System sollte in kürze auf der Karte auftauchen.
hängt vom kartenserver ab, bei uns sendet yanic jede minute einen multicast

2020-05-03 19:40 UTC, GitFlix commented on gateway.rst
> +   EOF
Wie besprochen: Ich hab mal versucht eine Erklärung einzubauen. Ist leider länger geworden als gedacht, gucks Dir mal an ob das so taugt oder über die Anleitung einfach hinausgeht.

2020-05-03 19:41 UTC, GitFlix commented on gateway.rst
> +Jetzt brauchenwir noch den dhcp innerhalb de FFSH-Netzes
Done.

2020-05-04 14:31 UTC, Grotax commented
merged

2020-05-04 14:31 UTC, closed without merging